/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_netty_resolver_dns_windows_NativeWrapper */

#ifndef _Included_io_netty_resolver_dns_windows_NativeWrapper
#define _Included_io_netty_resolver_dns_windows_NativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
	JNIEXPORT jobjectArray JNICALL Java_io_netty_resolver_dns_windows_WindowsResolverDnsServerAddressStreamProvider_adapters
	(JNIEnv*, jclass);

	JNIEXPORT jint JNI_OnLoad(JavaVM* vm, void* reserved);
	JNIEXPORT void JNI_OnUnload(JavaVM* vm, void* reserved);

#ifdef __cplusplus
}
#endif
#endif
