FROM mcr.microsoft.com/devcontainers/base:alpine
RUN apk -U upgrade && apk add \
    autoconf automake linux-headers libtool make tar libaio-dev openssl-dev apr-dev gcc \
    mandoc man-pages autoconf-doc automake-doc libtool-doc make-doc tar-doc gcc-doc \
    perf perf-bash-completion htop htop-doc strace strace-doc ripgrep ripgrep-doc \
    openjdk8-jdk openjdk8-doc openjdk8-src openjdk11-jdk openjdk11-doc openjdk11-src \
    openjdk17-jdk openjdk17-doc openjdk1-src openjdk21-jdk openjdk21-doc openjdk21-src \
    maven
