version: "3"

services:

  runtime-setup:
    image: netty:centos-7-24
    build:
      args:
        java_version : "24.0.1-zulu"

  build:
    image: netty:centos-7-24

  build-leak:
    image: netty:centos-7-24

  build-with-oio-testsuite:
    image: netty:centos-7-24

  build-boringssl-static:
    image: netty:centos-7-24

  build-leak-boringssl-static:
    image: netty:centos-7-24

  build-boringssl-snapshot:
    image: netty:centos-7-24

  shell:
    image: netty:centos-7-24
