version: "3"

services:

  runtime-setup:
    image: netty:ubi9-22
    build:
      args:
        java_version : "22.0.2-zulu"
      context: .
      dockerfile: Dockerfile.ubi9

  build:
    image: netty:ubi9-22

  build-leak:
    image: netty:ubi9-22

  build-boringssl-static:
    image: netty:ubi9-22

  build-leak-boringssl-static:
    image: netty:ubi9-22

  build-boringssl-snapshot:
    image: netty:ubi9-22

  shell:
    image: netty:ubi9-22
