version: "3"

services:

  runtime-setup:
    image: netty:centos-7-1.11
    build:
      args:
        java_version : "21.0.2-graalce"
      # See docker-compose.centos-7.111.yaml for why this cache ref is shared across centos-7.*.yaml.
      cache_from:
        - type=registry,ref=ghcr.io/netty/netty-build-cache:centos7
      cache_to:
        - type=registry,ref=ghcr.io/netty/netty-build-cache:centos7,mode=max,ignore-error=true

  build:
    image: netty:centos-7-1.11

  build-leak:
    image: netty:centos-7-1.11

  build-boringssl-static:
    image: netty:centos-7-1.11

  build-leak-boringssl-static:
    image: netty:centos-7-1.11

  build-boringssl-snapshot:
    image: netty:centos-7-1.11

  shell:
    image: netty:centos-7-1.11
