version: "3"

services:

  runtime-setup:
    image: netty:centos-7-1.11
    build:
      args:
        java_version : "21.0.2-graalce"

  build:
    image: netty:centos-7-1.11

  build-leak:
    image: netty:centos-7-1.11

  build-boringssl-static:
    image: netty:centos-7-1.11

  build-leak-boringssl-static:
    image: netty:centos-7-1.11

  build-boringssl-snapshot:
    image: netty:centos-7-1.11

  shell:
    image: netty:centos-7-1.11
