version: "3"

services:

  runtime-setup:
    image: netty:centos-6-21
    build:
      args:
        java_version : "21.0.5-zulu"

  build:
    image: netty:centos-6-21

  build-leak:
    image: netty:centos-6-21

  build-boringssl-static:
    image: netty:centos-6-21

  build-leak-boringssl-static:
    image: netty:centos-6-21

  build-boringssl-snapshot:
    image: netty:centos-6-21

  shell:
    image: netty:centos-6-21
