version: "3"

services:

  runtime-setup:
    image: netty:centos-7-23
    build:
      args:
        java_version : "23.0.2-zulu"

  build:
    image: netty:centos-7-23

  build-leak:
    image: netty:centos-7-23

  build-boringssl-static:
    image: netty:centos-7-23

  build-leak-boringssl-static:
    image: netty:centos-7-23

  build-boringssl-snapshot:
    image: netty:centos-7-23

  shell:
    image: netty:centos-7-23
