FROM centos:7.6.1810

ARG gcc_version=2023.10.18
ENV GCC_VERSION $gcc_version
ENV SOURCE_DIR /root/source

# Install requirements
RUN yum install -y wget tar git make redhat-lsb-core autoconf automake libtool glibc-devel libaio-devel openssl-devel apr-devel lksctp-tools unzip zip python3 libmpc-devel mpfr-devel gmp-devel gawk bison flex texinfo patchutils gcc gcc-c++ zlib-devel expat-devel

# Install Java
RUN yum install -y java-1.8.0-openjdk-devel

# Install newer GCC toolchain
RUN yum install -y centos-release-scl && \
    yum install -y devtoolset-11

RUN mkdir -p $SOURCE_DIR
WORKDIR $SOURCE_DIR

ENV PATH="/opt/riscv-gnu-toolchain/bin:${PATH}"

# Build riscv64 gcc toolchain
RUN bash -x <<-EOF
    source scl_source enable devtoolset-11
    set -eu
    cd $SOURCE_DIR
    git clone -b $GCC_VERSION https://github.com/riscv/riscv-gnu-toolchain
    cd riscv-gnu-toolchain
    ./configure --prefix=/opt/riscv-gnu-toolchain
    make linux -j --output-sync=target
EOF

RUN bash -x <<-EOF
    source scl_source enable devtoolset-11
    set -eu
    cd $SOURCE_DIR
    mkdir -p autoconf
    curl -L https://ftp.gnu.org/gnu/autoconf/autoconf-2.71.tar.gz | tar -xvzf - -C autoconf --strip-components 1
    cd autoconf
    ./configure --prefix=/opt/riscv-gnu-toolchain
    make
    make install
EOF

RUN bash -x <<-EOF
    source scl_source enable devtoolset-11
    # set -e
    cd $SOURCE_DIR
    rm -rf automake
    mkdir -p automake
    curl -L https://ftp.gnu.org/gnu/automake/automake-1.16.tar.gz | tar -xvzf - -C automake --strip-components 1
    cd automake
    cat > automake.patch <<PATCH
diff -bur automake-1.16/bin/automake.in  automake-1.16.new/bin/automake.in
--- automake-1.16/bin/automake.in       2018-02-26 01:13:58.000000000 +1100
+++ automake-1.16.new/bin/automake.in   2018-03-04 10:28:25.357886554 +1100
@@ -73,7 +73,8 @@
 use Automake::Language;
 use File::Basename;
 use File::Spec;
-use List::Util 'none';
+use List::Util 'reduce';
+sub none (&@) { my \\\$code=shift; reduce { \\\$a && !\\\$code->(local \\\$_ = \\\$b) } 1, @_; }
 use Carp;
 
 ## ----------------------- ##
PATCH
    patch -p1 < automake.patch
    ./configure --prefix=/opt/riscv-gnu-toolchain
    make
    make install
EOF

RUN bash -x <<-EOF
    source scl_source enable devtoolset-11
    set -eu
    cd $SOURCE_DIR
    mkdir -p libtool
    curl -L https://ftp.gnu.org/gnu/libtool/libtool-2.4.7.tar.gz | tar -xvzf - -C libtool --strip-components 1
    cd libtool
    ./configure --prefix=/opt/riscv-gnu-toolchain
    make
    make install
EOF

ENV JAVA_HOME="/usr/lib/jvm/java-1.8.0-openjdk/"

# Cleanup
RUN rm -rf $SOURCE_DIR
RUN yum clean all && \
    rm -rf /var/cache/yum
