version: "3"

services:

  runtime-setup:
    image: netty:centos-7-25
    build:
      args:
        java_version : "25.ea.31-open"

  build:
    image: netty:centos-7-25

  build-leak:
    image: netty:centos-7-25

  build-with-oio-testsuite:
    image: netty:centos-7-25

  build-boringssl-static:
    image: netty:centos-7-25

  build-leak-boringssl-static:
    image: netty:centos-7-25

  build-boringssl-snapshot:
    image: netty:centos-7-25

  build-boringssl-static-jdk8-tests:
    image: netty:centos-7-25

  shell:
    image: netty:centos-7-25
