/*
 * Copyright 2014 The Netty Project
 *
 * The Netty Project licenses this file to you under the Apache License, version 2.0 (the
 * "License"); you may not use this file except in compliance with the License. You may obtain a
 * copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package io.netty.handler.codec.http2;

import io.netty.buffer.ByteBuf;
import io.netty.channel.ChannelHandlerContext;

/**
 * Controls the inbound flow of data frames from the remote endpoint.
 */
public interface Http2InboundFlowController {

    /**
     * Applies inbound flow control to the given {@code DATA} frame.
     *
     * @param ctx the context from the handler where the frame was read.
     * @param streamId the subject stream for the frame.
     * @param data payload buffer for the frame.
     * @param padding the number of padding bytes found at the end of the frame.
     * @param endOfStream Indicates whether this is the last frame to be sent from the remote
     *            endpoint for this stream.
     */
    void applyFlowControl(ChannelHandlerContext ctx, int streamId, ByteBuf data, int padding,
            boolean endOfStream) throws Http2Exception;

    /**
     * Sets the global inbound flow control window size and updates all stream window sizes by the delta.
     * <p>
     * This method is used to apply the {@code SETTINGS_INITIAL_WINDOW_SIZE} value for an
     * outbound {@code SETTINGS} frame.
     * <p>
     * The connection stream windows will not be modified as a result of this call.
     * @param newWindowSize the new initial window size.
     * @throws Http2Exception thrown if any protocol-related error occurred.
     */
    void initialWindowSize(int newWindowSize) throws Http2Exception;

    /**
     * Gets the initial window size used as the basis for new stream flow control windows.
     */
    int initialWindowSize();

    /**
     * Sets the initial inbound flow control window size for a specific stream.
     * <p>
     * Note it is the responsibly of the caller to ensure that the the
     * initial {@code SETTINGS} frame is sent before this is called. It would
     * be considered a {@link Http2Error#PROTOCOL_ERROR} if a {@code WINDOW_UPDATE}
     * was generated by this method before the initial {@code SETTINGS} frame is sent.
     * @param ctx the context to use if a {@code WINDOW_UPDATE} is determined necessary.
     * @param streamId The stream to update.
     * @param newWindowSize the window size to apply to {@code streamId}
     * @throws Http2Exception thrown if any protocol-related error occurred.
     */
    void initialStreamWindowSize(ChannelHandlerContext ctx, int streamId, int newWindowSize) throws Http2Exception;

    /**
     * Obtain the initial window size for a specific stream.
     * @param streamId The stream id to get the initial window size for.
     * @return The initial window size for {@code streamId}.
     * @throws Http2Exception If no stream corresponding to {@code stream} could be found.
     */
    int initialStreamWindowSize(int streamId) throws Http2Exception;
}
