# Copyright 2019 The Netty Project
#
# The Netty Project licenses this file to you under the Apache License,
# version 2.0 (the "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at:
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

Args = --initialize-at-run-time=io.netty.handler.ssl.util.ThreadLocalInsecureRandom \
       --initialize-at-run-time=io.netty.handler.ssl.DefaultOpenSslCredential \
       --initialize-at-run-time=io.netty.handler.ssl.DefaultOpenSslKeyMaterial \
       --initialize-at-run-time=io.netty.handler.ssl.ExtendedOpenSslSession \
       --initialize-at-run-time=io.netty.handler.ssl.NonOwnedOpenSslCredential \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSsl \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslApplicationProtocolNegotiator \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslAsyncPrivateKeyMethod \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslCachingKeyMaterialProvider \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslCachingX509KeyManagerFactory \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslCertificateCompressionAlgorithm \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslCertificateCompressionConfig \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslCertificateException \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslClientContext \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslClientSessionCache \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslContext \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslContextOption \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslCredential \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslCredentialBuilder \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslCredentialPointer \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslDefaultApplicationProtocolNegotiator \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslEngine \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslInternalSession \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslKeyMaterial \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslKeyMaterialManager \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslKeyMaterialProvider \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslNpnApplicationProtocolNegotiator \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslParametersUtil \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslPrivateKey \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslPrivateKeyMethod \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslServerContext \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslServerSessionContext \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslSession \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslSessionCache \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslSessionContext \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslSessionId \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslSessionStats \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslSessionTicketKey \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslX509KeyManagerFactory \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSslX509TrustManagerWrapper \
       --initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslClientContext \
       --initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslContext \
       --initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslEngine \
       --initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslServerContext
